# -*- coding: utf-8 -*-
"""CHATBOT

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18pLNlXHs1HKcDfQI3dsK-65cZO0WepA4
"""

import re

# Define the chatbot's responses
responses = {
    "hello": "Hello! How can I assist you today?",
    "how are you": "I'm just a bot, but I'm here to help!",
    "what's your name": "I'm a chatbot created to assist you.",
    "bye": "Goodbye! Have a great day!",
    "tell me a joke": "Why don't scientists trust atoms? Because they make up everything!",
    "help": "Sure, I'd be happy to help. What do you need?",
    "weather": "I'm sorry, I can't provide real-time information. Please check a weather website.",
    "age": "I don't have an age. I'm a computer program.",
    "favorite color": "I don't have preferences. I'm here to assist you.",
    "how to contact support": "You can contact support by emailing support@example.com or calling 1-800-123-4567.",
    "order status": "To check your order status, log in to your account on our website.",
    "product information": "You can find detailed product information on our website's product pages.",
    "cancel order": "To cancel an order, log in to your account or contact our support team.",
    "payment methods": "We accept credit/debit cards, PayPal, and bank transfers as payment methods.",
    "tracking number": "Your tracking number can be found in your order confirmation email.",
    "default": "I'm sorry, I didn't quite understand that. Could you please rephrase?"
}

# Define patterns for rule-based responses
patterns = {
    re.compile(r'.*\bhello\b.*', re.IGNORECASE): "hello",
    re.compile(r'.*\bhow are you\b.*', re.IGNORECASE): "how are you",
    re.compile(r'.*\bwhat\'s your name\b.*', re.IGNORECASE): "what's your name",
    re.compile(r'.*\bbye\b.*', re.IGNORECASE): "bye",
    re.compile(r'.*\bjoke\b.*', re.IGNORECASE): "tell me a joke",
    re.compile(r'.*\bhelp\b.*', re.IGNORECASE): "help",
    re.compile(r'.*\bweather\b.*', re.IGNORECASE): "weather",
    re.compile(r'.*\bage\b.*', re.IGNORECASE): "age",
    re.compile(r'.*\bfavorite color\b.*', re.IGNORECASE): "favorite color",
    re.compile(r'.*\bhow to contact support\b.*', re.IGNORECASE): "how to contact support",
    re.compile(r'.*\border status\b.*', re.IGNORECASE): "order status",
    re.compile(r'.*\bproduct information\b.*', re.IGNORECASE): "product information",
    re.compile(r'.*\bcancel order\b.*', re.IGNORECASE): "cancel order",
    re.compile(r'.*\bpayment methods\b.*', re.IGNORECASE): "payment methods",
    re.compile(r'.*\btracking number\b.*', re.IGNORECASE): "tracking number"
}

# Chatbot interaction loop
def chatbot_response(user_input):
    for pattern, response_key in patterns.items():
        if pattern.match(user_input):
            return responses[response_key]
    return responses["default"]

print("Chatbot: Hello! How can I assist you today? (type 'bye' to exit)")

while True:
    user_input = input("You: ")
    if user_input.lower() == "bye":
        print("Chatbot: Goodbye! Have a great day!")
        break
    response = chatbot_response(user_input)
    print("Chatbot:", response)